# Generated by Django 5.0.7 on 2025-06-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=200)),
                ("total_pages", models.PositiveIntegerField()),
                ("publisher", models.CharField(blank=True, max_length=200, null=True)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_READ", "읽을 책"),
                            ("READING", "읽는 중"),
                            ("FINISHED", "다 읽음"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_page", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_books",
            },
        ),
        migrations.CreateModel(
            name="ReadingLogModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.userbookmodel",
                    ),
                ),
            ],
            options={
                "db_table": "reading_logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.userbookmodel",
                    ),
                ),
            ],
            options={
                "db_table": "memos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userbookmodel",
            index=models.Index(
                fields=["user", "status"], name="user_books_user_id_a5ff96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbookmodel",
            index=models.Index(
                fields=["title", "author"], name="user_books_title_0bc719_idx"
            ),
        ),
    ]
